### OBTAIN AUTH
POST https://zadania.aidevs.pl/token/{{ai-devs-task}}
Content-Type: application/json

{
  "apikey": "{{ai-devs-api-key}}"
}

> {%
    client.global.set("ai-devs-auth-token", response.body.token);
%}

### GET TASK
GET https://zadania.aidevs.pl/task/{{ai-devs-auth-token}}

### SEND ANSWER
POST https://zadania.aidevs.pl/answer/{{ai-devs-auth-token}}
Content-Type: application/json

{
  "answer": "https://cdn.renderform.io/KpCN42gOLei5fLa6GEkD/results/req-37be491b-b376-4319-af87-3393ac61cc75.jpg"
}

